import styles from './Layout.module.scss'
import Header from '@/components/header/Header'
import Sidebar from '@/components/sidebar/Sidebar'
import Head from 'next/head'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout(
	{
		children
	}: {
		children: React.ReactNode
	},
	title: string
) {
	return (
		<html lang='en'>
			<body>
				<Head>{title}</Head>
				<main className={styles.main}>
					<Sidebar />
					<section className={styles.content}>
						<Header />
						<div className={styles.wrapper}>{children}</div>
					</section>
				</main>
			</body>
		</html>
	)
}
