import styles from './Layout.module.scss'
import './globals.scss'
import Header from '@/components/header/Header'
import Sidebar from '@/components/sidebar/Sidebar'
import { Providers } from '@/store/provider'

export const metadata = {
	title: 'Tube Home Page',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<main className={styles.main}>
						<Sidebar />
						<section className={styles.content}>
							<Header />
							<div className={styles.wrapper}>{children}</div>
						</section>
					</main>
				</Providers>
			</body>
		</html>
	)
}
